### ISSUE TITLE
Rebalancer sometimes attempts to preempt synthetic tasks

### ISSUE THREAD

**Issue by mforsyth** [twosigma/Cook#140]
Somehow, the synthetic tasks attached to pending jobs (used to calculate hypothetical DRU layouts) are sometimes being included in the rebalancer's "task-ents-to-preempt".  When this happens, the attempt to transact the preemption of the synthetic task fails, because there is no database entity to update.  

Here's a a good log excerpt.  The rebalancer is attempting to preempt 2 instances.  The first one in the list is an actual running instance.   You can see that it has a :instance/start-time and a :db/id .  The second task has neither :instance/start-time nor :db/id ; it must be a synthetic task.

2016-06-16 10:18:28,621 INFO  cook.mesos.rebalancer [async-thread-macro-7] - Tasks to preempt: [{:instance/hostname 172.20.20.20, :instance/start-time #inst "2016-06-16T14:18:27.805-00:00", :job/_instance {:job/resource #{{:resource/amount 36948.0, :resource/type :resource.type/mem, :db/id 17592186656106} {:resource/amount 2.0, :resource/type :resource.type/cpus, :db/id 17592186656105}}, :job/priority 4, :job/user simmer2, :db/id 17592186656104}, :db/id 17592186656636} {:job/_instance {:job/resource #{{:resource/amount 4.0, :resource/type :resource.type/cpus, :db/id 17592186656153} {:resource/amount 48264.0, :resource/type :resource.type/mem, :db/id 17592186656154}}, :job/priority 42, :job/user simmer14, :db/id 17592186656152}, :instance/status :instance.status/running, :instance/hostname slave3}]
2016-06-16 10:18:28,632 DEBUG cook.mesos.scheduler [async-dispatch-46] - Updating state of job {:db/id 17592186656104} due to update of instance 17592186656636
2016-06-16 10:18:28,633 WARN  cook.mesos.rebalancer [async-thread-macro-7] - Failed to transact preemption
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: :db.error/not-an-entity Unable to resolve entity:  in datom [nil :instance/reason-code 1002]
    at datomic.promise$throw_executionexception_if_throwable.invoke(promise.clj:10)
    at datomic.promise$settable_future$reify__6755.deref(promise.clj:54)
    at clojure.core$deref.invoke(core.clj:2200)
    at cook.mesos.rebalancer$rebalance_BANG_$fn__27385$fn__27386.invoke(rebalancer.clj:311)
    at cook.mesos.rebalancer$rebalance_BANG_$fn__27385.invoke(rebalancer.clj:303)
    at cook.mesos.rebalancer$rebalance_BANG_.invoke(rebalancer.clj:302)
    at cook.mesos.rebalancer$start_rebalancer_BANG_$fn__27425.invoke(rebalancer.clj:373)
    at chime$chime_at$fn__26207$state_machine__5615__auto____26208$fn__26210$fn__26216.invoke(chime.clj:68)
    at clojure.core.async$thread_call$fn__5812.invoke(async.clj:405)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: :db.error/not-an-entity Unable to resolve entity:  in datom [nil :instance/reason-code 1002]
    at datomic.error$arg.invoke(error.clj:57)
    at datomic.error$arg.invoke(error.clj:55)
    at datomic.db$require_id.invokePrim(db.clj:548)
    at datomic.db.ProcessInpoint.inject(db.clj:2304)
    at datomic.transaction$inject_all$fn__7009.invoke(transaction.clj:127)
    at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:63)
    at clojure.core.protocols$fn__6093.invoke(protocols.clj:98)
    at clojure.core.protocols$fn__6057$G__6052__6066.invoke(protocols.clj:19)
    at clojure.core.protocols$seq_reduce.invoke(protocols.clj:31)
    at clojure.core.protocols$fn__6076.invoke(protocols.clj:60)
    at clojure.core.protocols$fn__6031$G__6026__6044.invoke(protocols.clj:13)
    at clojure.core$reduce.invoke(core.clj:6289)
    at datomic.transaction$inject_all.invoke(transaction.clj:123)
    at datomic.peer.Connection.transactAsync(peer.clj:338)
    at datomic.peer.Connection.transact(peer.clj:331)
    at datomic.api$transact.invoke(api.clj:94)
    ... 10 more

This doesn't cause any huge short-term issues;  the attempt to pre-empt fails but the error is caught, and since there was never a real task in the first place, we don't actually WANT to update the database or tell Mesos to do anything regarding the task.  

However, it does imply that the Rebalancer's algorithm isn't working quite right.  The way I'm looking at it, If a preemption decision involves killing some tasks that were never started in order to make room for other pending tasks, the whole analysis about which set of tasks to preempt must be relying in part on bad information.

**Comment by wyegelwel** [comment]
I *think* this is caused by [get-pending-job-ents](https://github.com/twosigma/Cook/blob/master/scheduler/src/cook/mesos/util.clj#L108) not including jobs whose instances are in state "unknown" (scheduled but not confirmed started by executor) and [get-running-task-ents](https://github.com/twosigma/Cook/blob/master/scheduler/src/cook/mesos/util.clj#L127) including tasks in state "running" and "unknown" so those jobs such that they are scheduled but not started will be double counted as both waiting and running.
