### ISSUE TITLE
Reconciliation with Fenzo on startup can fail with a NullPointerException

### ISSUE THREAD

**Issue by mforsyth** [twosigma/Cook#163]
When Cook starts up, it attempts to reconcile its knowledge of tasks with Fenzo, but if there are any tasks that found to be in running state, this attempt leads to a NullPointerException within Fenzo:

2016-07-29 10:21:48,987 ERROR cook.mesos.scheduler [clojure-agent-send-off-pool-5] - Reconciliation error
java.lang.IllegalStateException: java.lang.NullPointerException
at com.netflix.fenzo.TaskScheduler$2.call(TaskScheduler.java:811)
at com.netflix.fenzo.TaskScheduler$2.call(TaskScheduler.java:804)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
at cook.mesos.scheduler$reconcile_tasks.invokeStatic(scheduler.clj:789)
at cook.mesos.scheduler$reconcile_tasks.invoke(scheduler.clj:769)
at cook.mesos.scheduler$create_datomic_scheduler$fn__21044$fn__21045.invoke(scheduler.clj:1072)
at clojure.core$binding_conveyor_fn$fn__4676.invoke(core.clj:1938)
at clojure.lang.AFn.call(AFn.java:18)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
at com.netflix.fenzo.AssignableVMs.createAvmIfAbsent(AssignableVMs.java:134)
at com.netflix.fenzo.AssignableVMs.setTaskAssigned(AssignableVMs.java:104)
at com.netflix.fenzo.TaskScheduler$2.call(TaskScheduler.java:808)
... 16 more

**Comment by wyegelwel** [comment]
I think this has been addressed by filtering artificial instances. Is that correct?
