### ISSUE TITLE
Spread load evenly?

### ISSUE THREAD

**Issue by m4ce** [twosigma/Cook#182]
Hi,

it's me again :) We are really happy with Cook so far and we are moving a lot of things over to it. Thanks for the great work you have been doing. I also wrote a python library (which you can find at https://github.com/m4ce/cook-jobclient-python) that implements some basic jobclient functionality.

I noticed that often jobs get scheduled on the same node even though the cluster is idle and there are something like 10 machines all spec'ed the same.

Is there anyway to spread the load more evenly in the cluster? The jobs are currently hammering the storage on a single box :( I don't see any reason why the other boxes should not get tasks to run.

Thanks,
Matteo

**Comment by wyegelwel** [comment]
Hey Matteo! I'm glad to hear you are getting good use out of cook.

We have cook configured to try to pack hosts as fully as possible which could explain why you are seeing all the jobs on one host. As a first step you can remove the bin packing line in the scheduler.clj file which should spread things out more evenly though may not solve the problem for you.

I'm on my phone at the moment so my apologizes for the short reply.

**Comment by m4ce** [comment]
Hi @wyegelwel,

ok, thanks, I will try this out and let you know how I get along with it.

By the way, this morning we found cook in an unusable state. It kept reporting 'Found 0 VMs with non-zero offers to assign from'. After checking the logs, it appears that last Saturday at 1am, it stopped working:

```
2016-09-17 01:02:55,398 INFO  com.netflix.fenzo.AssignableVMs [async-thread-macro-2] - Host cpu03 not available for assignments
2016-09-17 01:02:55,398 INFO  com.netflix.fenzo.AssignableVMs [async-thread-macro-2] - Host cpu10 not available for assignments
2016-09-17 01:02:55,398 INFO  com.netflix.fenzo.TaskScheduler [async-thread-macro-2] - Found 0 VMs with non-zero offers to assign from
2016-09-17 01:02:55,398 INFO  com.netflix.fenzo.TaskScheduler [async-thread-macro-2] - Purging inactive VMs
2016-09-17 01:02:55,398 INFO  com.netflix.fenzo.AssignableVMs [async-thread-macro-2] - Removed inactive host cpu05
2016-09-17 01:02:55,398 INFO  com.netflix.fenzo.AssignableVMs [async-thread-macro-2] - Removed inactive host cpu04
2016-09-17 01:02:55,398 INFO  com.netflix.fenzo.AssignableVMs [async-thread-macro-2] - Removed inactive host cpu06
2016-09-17 01:02:55,398 INFO  com.netflix.fenzo.AssignableVMs [async-thread-macro-2] - Removed inactive host cpu01
2016-09-17 01:02:55,398 INFO  com.netflix.fenzo.AssignableVMs [async-thread-macro-2] - Removed inactive host cpu09
VMs [async-thread-macro-2] - Removed inactive host cpu08
2016-09-17 01:02:55,398 INFO  com.netflix.fenzo.AssignableVMs [async-thread-macro-2] - Removed inactive host cpu02
2016-09-17 01:02:55,398 INFO  com.netflix.fenzo.AssignableVMs [async-thread-macro-2] - Removed inactive host cpu07
2016-09-17 01:02:55,398 INFO  com.netflix.fenzo.AssignableVMs [async-thread-macro-2] - Removed inactive host cpu03
2016-09-17 01:02:55,398 INFO  com.netflix.fenzo.AssignableVMs [async-thread-macro-2] - Removed inactive host cpu10
2016-09-17 01:02:56,388 INFO  com.netflix.fenzo.TaskScheduler [async-thread-macro-2] - Found 0 VMs with non-zero offers to assign from
``` 
It never recovered since then. This morning, I restarted cook and it started working again. I also checked the mesos master logs but didn't see much in there.

I am using a snapshot of cook from master up to this commit (https://github.com/twosigma/Cook/commit/169228602111d1065ab99933687a6c789d3d458e), plus my patch for the docker force pull image.

Have you ever seen this behavior before?

Thanks,
Matteo

**Comment by wyegelwel** [comment]
Hey Matteo!

I've seen that once before but couldn't reproduce it again to track it
down. I think cook is not declining all offers from mesos and they are
getting sent to the abyss. Until I can track it down there is an easy work
around which is suggested by mesosphere anyway if you have more then 1
framework connected to the cluster. Set an offer timeout on mesos master so
offers will expire after some time. 1 minute is plenty of time.

**Comment by m4ce** [comment]
@wyegelwel, thanks for letting me know :)

**Comment by RKREpsilon** [comment]
By the way.. I've tried to pull the latest code from master.. and when I run cook, soon after submitting a tes job (that always worked before), I get the following:

```
2016-09-19 20:24:18,426 INFO  com.netflix.fenzo.TaskScheduler [async-thread-macro-2] - Task 356edc9b-f543-4b55-9fa3-11d053d79f09: found successful assignment on host cpu03
2016-09-19 20:24:18,474 INFO  cook.mesos.scheduler [async-thread-macro-2] - Launching 1 tasks
2016-09-19 20:24:18,474 INFO  cook.mesos.scheduler [async-thread-macro-2] - Upgrading 0 tasks from backfilled to proper
2016-09-19 20:24:18,477 INFO  cook.mesos.scheduler [async-thread-macro-2] - Matched tasks ([[:job/allowed-to-start? 17592186052313] {:instance/progress 0, :instance/executor-id 356e
dc9b-f543-4b55-9fa3-11d053d79f09, :instance/ports #object[java.util.ArrayList 0x38b9d0a7 []], :instance/task-id 356edc9b-f543-4b55-9fa3-11d053d79f09, :instance/preempted? false, :in
stance/start-time #inst "2016-09-19T20:24:18.430-00:00", :instance/backfilled? false, :instance/slave-id 5cbb4cd9-cefd-4daa-a421-376d89328ab6-S1, :db/id #db/id[:db.part/user -100013
2], :job/_instance 17592186052313, :instance/status :instance.status/unknown, :instance/hostname cpu03}])
2016-09-19 20:24:18,478 ERROR cook.mesos.scheduler [async-thread-macro-2] - Error in match: nil
clojure.lang.ArityException: Wrong number of args (1) passed to: core/into
        at clojure.lang.AFn.throwArity(AFn.java:429)
        at clojure.lang.AFn.invoke(AFn.java:32)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:646)
        at clojure.core$apply.invoke(core.clj:641)
        at cook.mesos.task$eval17680$fn__17681.invoke(task.clj:21)
        at clojure.lang.MultiFn.invoke(MultiFn.java:229)
        at plumbing.core$map_vals$fn__228.invoke(core.clj:36)
        at clojure.core$fn__6939$fn__6941.invoke(core.clj:6557)
        at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
        at clojure.core.protocols$fn__6742.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__6742.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__6684$G__6679__6697.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6545)
        at clojure.core$fn__6939.invokeStatic(core.clj:6547)
        at clojure.core$fn__6939.invoke(core.clj:6547)
        at clojure.core.protocols$fn__6763$G__6758__6772.invoke(protocols.clj:174)
        at clojure.core$reduce_kv.invokeStatic(core.clj:6573)
        at clojure.core$reduce_kv.invoke(core.clj:6564)
        at plumbing.core$map_vals.invokeStatic(core.clj:36)
        at plumbing.core$map_vals.invoke(core.clj:32)
        at cook.mesos.task$resources_by_role$fn__17684.invoke(task.clj:35)
        at plumbing.core$map_vals$fn__228.invoke(core.clj:36)
        at clojure.core$fn__6939$fn__6941.invoke(core.clj:6557)
        at plumbing.core$map_vals$fn__228.invoke(core.clj:36)
        at clojure.core$fn__6939$fn__6941.invoke(core.clj:6557)
        at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
        at clojure.core.protocols$fn__6742.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__6742.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__6684$G__6679__6697.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6545)
        at clojure.core$fn__6939.invokeStatic(core.clj:6547)
        at clojure.core$fn__6939.invoke(core.clj:6547)
        at clojure.core.protocols$fn__6763$G__6758__6772.invoke(protocols.clj:174)
        at clojure.core$reduce_kv.invokeStatic(core.clj:6573)
        at clojure.core$reduce_kv.invoke(core.clj:6564)
        at plumbing.core$map_vals.invokeStatic(core.clj:36)
        at plumbing.core$map_vals.invoke(core.clj:32)
        at cook.mesos.task$resources_by_role.invokeStatic(task.clj:32)
        at cook.mesos.task$resources_by_role.invoke(task.clj:23)
        at cook.mesos.task$compile_mesos_messages.invokeStatic(task.clj:168)
        at cook.mesos.task$compile_mesos_messages.invoke(task.clj:162)
        at cook.mesos.scheduler$handle_resource_offers_BANG_$fn__18995.invoke(scheduler.clj:671)
        at cook.mesos.scheduler.proxy$java.lang.Object$Callable$7da976d4.call(Unknown Source)
        at com.codahale.metrics.Timer.time(Timer.java:99)
        at cook.mesos.scheduler$handle_resource_offers_BANG_.invokeStatic(scheduler.clj:568)
        at cook.mesos.scheduler$handle_resource_offers_BANG_.invoke(scheduler.clj:560)
        at cook.mesos.scheduler$make_offer_handler$fn__19156$fn__19157.invoke(scheduler.clj:734)
        at cook.mesos.scheduler$make_offer_handler$fn__19156.invoke(scheduler.clj:722)
        at clojure.core.async$thread_call$fn__11562.invoke(async.clj:434)
        at cook.mesos.scheduler$make_offer_handler$fn__19156.invoke(scheduler.clj:722)
        at clojure.core.async$thread_call$fn__11562.invoke(async.clj:434)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

Would you know what the problem is?

**Comment by m4ce** [comment]
By the way.. I've tried to pull the latest code from master.. and when I run cook, soon after submitting a test job (that always worked before), I get the following:
```
2016-09-19 20:24:18,426 INFO  com.netflix.fenzo.TaskScheduler [async-thread-macro-2] - Task 356edc9b-f543-4b55-9fa3-11d053d79f09: found successful assignment on host cpu03
2016-09-19 20:24:18,474 INFO  cook.mesos.scheduler [async-thread-macro-2] - Launching 1 tasks
2016-09-19 20:24:18,474 INFO  cook.mesos.scheduler [async-thread-macro-2] - Upgrading 0 tasks from backfilled to proper
2016-09-19 20:24:18,477 INFO  cook.mesos.scheduler [async-thread-macro-2] - Matched tasks ([[:job/allowed-to-start? 17592186052313] {:instance/progress 0, :instance/executor-id 356e
dc9b-f543-4b55-9fa3-11d053d79f09, :instance/ports #object[java.util.ArrayList 0x38b9d0a7 []], :instance/task-id 356edc9b-f543-4b55-9fa3-11d053d79f09, :instance/preempted? false, :in
stance/start-time #inst "2016-09-19T20:24:18.430-00:00", :instance/backfilled? false, :instance/slave-id 5cbb4cd9-cefd-4daa-a421-376d89328ab6-S1, :db/id #db/id[:db.part/user -100013
2], :job/_instance 17592186052313, :instance/status :instance.status/unknown, :instance/hostname cpu03}])
2016-09-19 20:24:18,478 ERROR cook.mesos.scheduler [async-thread-macro-2] - Error in match: nil
clojure.lang.ArityException: Wrong number of args (1) passed to: core/into
        at clojure.lang.AFn.throwArity(AFn.java:429)
        at clojure.lang.AFn.invoke(AFn.java:32)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:646)
        at clojure.core$apply.invoke(core.clj:641)
        at cook.mesos.task$eval17680$fn__17681.invoke(task.clj:21)
        at clojure.lang.MultiFn.invoke(MultiFn.java:229)
        at plumbing.core$map_vals$fn__228.invoke(core.clj:36)
        at clojure.core$fn__6939$fn__6941.invoke(core.clj:6557)
        at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
        at clojure.core.protocols$fn__6742.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__6742.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__6684$G__6679__6697.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6545)
        at clojure.core$fn__6939.invokeStatic(core.clj:6547)
        at clojure.core$fn__6939.invoke(core.clj:6547)
        at clojure.core.protocols$fn__6763$G__6758__6772.invoke(protocols.clj:174)
        at clojure.core$reduce_kv.invokeStatic(core.clj:6573)
        at clojure.core$reduce_kv.invoke(core.clj:6564)
        at plumbing.core$map_vals.invokeStatic(core.clj:36)
        at plumbing.core$map_vals.invoke(core.clj:32)
        at cook.mesos.task$resources_by_role$fn__17684.invoke(task.clj:35)
        at plumbing.core$map_vals$fn__228.invoke(core.clj:36)
        at clojure.core$fn__6939$fn__6941.invoke(core.clj:6557)
        at plumbing.core$map_vals$fn__228.invoke(core.clj:36)
        at clojure.core$fn__6939$fn__6941.invoke(core.clj:6557)
        at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
        at clojure.core.protocols$fn__6742.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__6742.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__6684$G__6679__6697.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6545)
        at clojure.core$fn__6939.invokeStatic(core.clj:6547)
        at clojure.core$fn__6939.invoke(core.clj:6547)
        at clojure.core.protocols$fn__6763$G__6758__6772.invoke(protocols.clj:174)
        at clojure.core$reduce_kv.invokeStatic(core.clj:6573)
        at clojure.core$reduce_kv.invoke(core.clj:6564)
        at plumbing.core$map_vals.invokeStatic(core.clj:36)
        at plumbing.core$map_vals.invoke(core.clj:32)
        at cook.mesos.task$resources_by_role.invokeStatic(task.clj:32)
        at cook.mesos.task$resources_by_role.invoke(task.clj:23)
        at cook.mesos.task$compile_mesos_messages.invokeStatic(task.clj:168)
        at cook.mesos.task$compile_mesos_messages.invoke(task.clj:162)
        at cook.mesos.scheduler$handle_resource_offers_BANG_$fn__18995.invoke(scheduler.clj:671)
        at cook.mesos.scheduler.proxy$java.lang.Object$Callable$7da976d4.call(Unknown Source)
        at com.codahale.metrics.Timer.time(Timer.java:99)
        at cook.mesos.scheduler$handle_resource_offers_BANG_.invokeStatic(scheduler.clj:568)
        at cook.mesos.scheduler$handle_resource_offers_BANG_.invoke(scheduler.clj:560)
        at cook.mesos.scheduler$make_offer_handler$fn__19156$fn__19157.invoke(scheduler.clj:734)
        at cook.mesos.scheduler$make_offer_handler$fn__19156.invoke(scheduler.clj:722)
        at clojure.core.async$thread_call$fn__11562.invoke(async.clj:434)
        at cook.mesos.scheduler$make_offer_handler$fn__19156.invoke(scheduler.clj:722)
        at clojure.core.async$thread_call$fn__11562.invoke(async.clj:434)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```
Would you know what the problem is?

**Comment by mforsyth** [comment]
@m4ce @wyegelwel I believe that's the same problem I noticed when trying to run a simulation test on Travis.   It will happen when a set of offers collectively contains only 1 port range.  This PR should fix it:  https://github.com/twosigma/Cook/pull/183
