### ISSUE TITLE
test_docker_port_mapping is flaky

### ISSUE THREAD

**Issue by shamsimam** [twosigma/Cook#587]
```
======================================================================
ERROR: test_docker_port_mapping (tests.cook.test_basic.CookTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/twosigma/Cook/integration/tests/cook/test_basic.py", line 1149, in test_docker_port_mapping
    job = util.wait_for_job(self.cook_url, job_uuid, 'running')
  File "/home/travis/build/twosigma/Cook/integration/tests/cook/util.py", line 308, in wait_for_job
    return wait_for_jobs(cook_url, [job_id], status, max_delay)[0]
  File "/home/travis/build/twosigma/Cook/integration/tests/cook/util.py", line 321, in wait_for_jobs
    response = wait_until(query, predicate, max_wait_ms=max_delay, wait_interval_ms=2000)
  File "/home/travis/build/twosigma/Cook/integration/tests/cook/util.py", line 242, in wait_until
    return wait_until_inner()
  File "/home/travis/build/twosigma/Cook/integration/.eggs/retrying-1.3.3-py3.6.egg/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/home/travis/build/twosigma/Cook/integration/.eggs/retrying-1.3.3-py3.6.egg/retrying.py", line 212, in call
    raise attempt.get()
  File "/home/travis/build/twosigma/Cook/integration/.eggs/retrying-1.3.3-py3.6.egg/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/home/travis/.pyenv/versions/3.6.2/lib/python3.6/site-packages/six-1.11.0-py3.6.egg/six.py", line 693, in reraise
    raise value
  File "/home/travis/build/twosigma/Cook/integration/.eggs/retrying-1.3.3-py3.6.egg/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/home/travis/build/twosigma/Cook/integration/tests/cook/util.py", line 236, in wait_until_inner
    raise RuntimeError(error_msg)
RuntimeError: wait_until condition not yet met, retrying...
-------------------- >> begin captured logging << --------------------
tests.cook.util: INFO: Using cook url http://localhost:12321
tests.cook.util: INFO: Using cook url http://localhost:12321
tests.cook.util: DEBUG: Waiting for connection to cook...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET / HTTP/1.1" 404 None
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /settings HTTP/1.1" 200 None
urllib3.connectionpool: DEBUG: http://172.17.0.4:5050 "GET /redirect HTTP/1.1" 307 0
tests.cook.util: INFO: Using mesos url http://172.17.0.4:5050
tests.cook.util: DEBUG: Waiting for connection to cook...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET / HTTP/1.1" 404 None
tests.cook.util: INFO: {'jobs': [{'command': 'python -m http.server 8080', 'cpus': 1, 'max_retries': 1, 'mem': 256, 'name': 'echo', 'priority': 1, 'uuid': 'd225dd6a-b0cf-4098-a1e5-16af093e5771', 'ports': 2, 'container': {'type': 'DOCKER', 'docker': {'image': 'python:3.6', 'network': 'BRIDGE', 'port-mapping': [{'host-port': 0, 'container-port': 8080}, {'host-port': 1, 'container-port': 9090, 'protocol': 'udp'}]}}}]}
urllib3.connectionpool: DEBUG: http://localhost:12321 "POST /rawscheduler HTTP/1.1" 201 None
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status waiting, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status waiting, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status waiting, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status waiting, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status waiting, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Job d225dd6a-b0cf-4098-a1e5-16af093e5771 has status completed, expecting running.
tests.cook.util: DEBUG: wait_until condition not yet met, retrying...
urllib3.connectionpool: DEBUG: http://localhost:12321 "GET /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 200 None
tests.cook.util: INFO: Timeout exceeded waiting for condition. Details: b'[{"constraints":[],"labels":{},"mem":256.0,"max_retries":1,"max_runtime":9223372036854775807,"name":"echo","gpus":0,"disable_mea_culpa_retries":false,"command":"python -m http.server 8080","state":"failed","env":{},"framework_id":"cook-framework-1","ports":2,"instances":[{"reason_code":3004,"reason_string":"Invalid task","start_time":1511305144266,"executor_id":"e0d7395b-a8a0-4804-8d80-00dd79429d5d","hostname":"172.17.0.7","slave_id":"c6006016-7803-4d19-81fa-241384f4824a-S1","preempted":false,"end_time":1511305144423,"backfilled":false,"ports":[32000,32001],"status":"failed","task_id":"e0d7395b-a8a0-4804-8d80-00dd79429d5d","executor":"mesos","progress":0}],"priority":1,"status":"completed","submit_time":1511305134596,"uuid":"d225dd6a-b0cf-4098-a1e5-16af093e5771","uris":[],"user":"vagrant","retries_remaining":0,"cpus":1.0}]'
urllib3.connectionpool: DEBUG: http://localhost:12321 "DELETE /rawscheduler?job=d225dd6a-b0cf-4098-a1e5-16af093e5771 HTTP/1.1" 204 0
--------------------- >> end captured logging << ---------------------

```

**Comment by DaoWen** [comment]
I also had this test fail today on Travis.
