### ISSUE TITLE
Fair resources sharing between multiple users with same priority

### ISSUE THREAD

**Issue by 2m4t** [twosigma/Cook#96]
If  two users run two different spark tasks (with the same priority) requiring all the cpus in the cluster, should the scheduler split the cluster 50/50 between the two? because what I see is that the first task served is the one that take all the resources until it ends.

**Comment by icexelloss** [comment]
Cook scheduler will eventually split the cluster 50/50. It should reach
50/50 state a few minutes after the second user comes in.

**Comment by LinuxContainerSecurity** [comment]
So maybe I do something wrong. I have a small cluster of 4 VMs ( 3 cores, 30 GB of Ram and 30 GB of disk each one) running Mesos. I am using a simple task like SparkPi to test the behavior of the Cook scheduler with multiple users running spark jobs. From my understanding specifying spark.core.max=12 and spark.cook.cores.per.job.max=3 (here I do not understand why it is called max if actually it is the required number of free cores necessary to run a spark executor on a Mesos slave) each task will try to run 4 spark executors (one per VM) occupying all available cores. With this configuration I expected that after the first spark task has taken all the resources, the scheduler regains half of them and runs two new executors for the second spark task. However what I see is that the second spark task has to wait until the end of the first one (even for hours). Where am I wrong?

**Comment by LinuxContainerSecurity** [comment]
I made some progress but not enough to trigger any re-balancing. I am not familiar with clojure but debugging the code I have seen that there are some problems within the [rebalancer](https://github.com/twosigma/Cook/blob/master/scheduler/src/cook/mesos/rebalancer.clj). First it is not able to parse correctly the stats from Mesos (I am running Mesos 0.26 on my cluster) since the get-mesos-utilization function is always returning nil. I have also seen that the :rebalancer/config table is not set by default so the parameters loaded from the database are empty. After I fixed both these issues I got these exceptions:
2016-02-22 18:26:08,901 WARN  cook.mesos.rebalancer [async-thread-macro-5] - Failed to transact preemption
java.util.concurrent.ExecutionException: java.io.FileNotFoundException: Could not locate metatransaction/core__init.class or metatransaction/core.clj on classpath.
        at datomic.promise$throw_executionexception_if_throwable.invoke(promise.clj:10)
        at datomic.promise$settable_future$reify__6755.deref(promise.clj:54)
        at clojure.core$deref.invoke(core.clj:2200)
        at cook.mesos.rebalancer$rebalance_BANG_$fn__11778$fn__11779.invoke(rebalancer.clj:310)
        at cook.mesos.rebalancer$rebalance_BANG_$fn__11778.invoke(rebalancer.clj:302)
        at cook.mesos.rebalancer$rebalance_BANG_.invoke(rebalancer.clj:301)
        at cook.mesos.rebalancer$start_rebalancer_BANG_$fn__11812.invoke(rebalancer.clj:385)
        at chime$chime_at$fn__10635$state_machine__4452__auto____10636$fn__10638$fn__10644.invoke(chime.clj:68)
        at clojure.core.async$thread_call$fn__4631.invoke(async.clj:405)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: Could not locate metatransaction/core__init.class or metatransaction/core.clj on classpath.
        at clojure.core$eval12937$fn__12938.invoke(NO_SOURCE_FILE)
        at datomic.error$deserialize_exception.invoke(error.clj:135)
        at datomic.peer.Connection.notify_error(peer.clj:399)
        at datomic.connector$fn__8698.invoke(connector.clj:169)
        at clojure.lang.MultiFn.invoke(MultiFn.java:231)
        at datomic.connector$create_hornet_notifier$fn__8704$fn__8705$fn__8708$fn__8709.invoke(connector.clj:194)
        at datomic.connector$create_hornet_notifier$fn__8704$fn__8705$fn__8708.invoke(connector.clj:189)
        at datomic.connector$create_hornet_notifier$fn__8704$fn__8705.invoke(connector.clj:187)
        at clojure.core$binding_conveyor_fn$fn__4145.invoke(core.clj:1910)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        ... 3 more
2016-02-22 18:26:08,920 WARN  cook.mesos.rebalancer [async-thread-macro-5] - Failed to transact preemption
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: :db.error/not-an-entity Unable to resolve entity:  in datom [nil :instance/preempted? true]
        at datomic.promise$throw_executionexception_if_throwable.invoke(promise.clj:10)
        at datomic.promise$settable_future$reify__6755.deref(promise.clj:54)
        at clojure.core$deref.invoke(core.clj:2200)
        at cook.mesos.rebalancer$rebalance_BANG_$fn__11778$fn__11779.invoke(rebalancer.clj:310)
        at cook.mesos.rebalancer$rebalance_BANG_$fn__11778.invoke(rebalancer.clj:302)
        at cook.mesos.rebalancer$rebalance_BANG_.invoke(rebalancer.clj:301)
        at cook.mesos.rebalancer$start_rebalancer_BANG_$fn__11812.invoke(rebalancer.clj:385)
        at chime$chime_at$fn__10635$state_machine__4452__auto____10636$fn__10638$fn__10644.invoke(chime.clj:68)
        at clojure.core.async$thread_call$fn__4631.invoke(async.clj:405)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: :db.error/not-an-entity Unable to resolve entity:  in datom [nil :instance/preempted? true]
        at datomic.error$arg.invoke(error.clj:57)
        at datomic.error$arg.invoke(error.clj:55)
        at datomic.db$require_id.invokePrim(db.clj:548)
        at datomic.db.ProcessInpoint.inject(db.clj:2304)
        at datomic.transaction$inject_all$fn__7009.invoke(transaction.clj:127)
        at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:63)
        at clojure.core.protocols$fn__6093.invoke(protocols.clj:98)
        at clojure.core.protocols$fn__6057$G__6052__6066.invoke(protocols.clj:19)
        at clojure.core.protocols$seq_reduce.invoke(protocols.clj:31)
        at clojure.core.protocols$fn__6076.invoke(protocols.clj:60)
        at clojure.core.protocols$fn__6031$G__6026__6044.invoke(protocols.clj:13)
        at clojure.core$reduce.invoke(core.clj:6289)
        at datomic.transaction$inject_all.invoke(transaction.clj:123)
        at datomic.peer.Connection.transactAsync(peer.clj:338)
        at datomic.peer.Connection.transact(peer.clj:331)
        at datomic.api$transact.invoke(api.clj:94)
        ... 10 more
>

**Comment by DaoWen** [comment]
@2m4t - I'm closing this issue since there has been no activity in the last two years. If you're still using Cook and having similar rebalancing problems, feel free to open a new issue.
